// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// isInteraction
bool isInteraction(RawVector x1, RawVector x2);
RcppExport SEXP _iqtcat_isInteraction(SEXP x1SEXP, SEXP x2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< RawVector >::type x2(x2SEXP);
    rcpp_result_gen = Rcpp::wrap(isInteraction(x1, x2));
    return rcpp_result_gen;
END_RCPP
}
// interactionIndices
DataFrame interactionIndices(RawMatrix x, CharacterVector chr, NumericVector pos, double minDist);
RcppExport SEXP _iqtcat_interactionIndices(SEXP xSEXP, SEXP chrSEXP, SEXP posSEXP, SEXP minDistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pos(posSEXP);
    Rcpp::traits::input_parameter< double >::type minDist(minDistSEXP);
    rcpp_result_gen = Rcpp::wrap(interactionIndices(x, chr, pos, minDist));
    return rcpp_result_gen;
END_RCPP
}
// testIndices
DataFrame testIndices(RawMatrix x, IntegerVector inx1, IntegerVector inx2, CharacterVector chr, NumericVector pos, double minDist);
RcppExport SEXP _iqtcat_testIndices(SEXP xSEXP, SEXP inx1SEXP, SEXP inx2SEXP, SEXP chrSEXP, SEXP posSEXP, SEXP minDistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type inx1(inx1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type inx2(inx2SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pos(posSEXP);
    Rcpp::traits::input_parameter< double >::type minDist(minDistSEXP);
    rcpp_result_gen = Rcpp::wrap(testIndices(x, inx1, inx2, chr, pos, minDist));
    return rcpp_result_gen;
END_RCPP
}
// cor_x
double cor_x(RawVector x1, RawVector x2, RawVector y1, RawVector y2);
RcppExport SEXP _iqtcat_cor_x(SEXP x1SEXP, SEXP x2SEXP, SEXP y1SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< RawVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< RawVector >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< RawVector >::type y2(y2SEXP);
    rcpp_result_gen = Rcpp::wrap(cor_x(x1, x2, y1, y2));
    return rcpp_result_gen;
END_RCPP
}
// corDist_x
double corDist_x(RawVector x1, RawVector x2, RawVector y1, RawVector y2);
RcppExport SEXP _iqtcat_corDist_x(SEXP x1SEXP, SEXP x2SEXP, SEXP y1SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< RawVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< RawVector >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< RawVector >::type y2(y2SEXP);
    rcpp_result_gen = Rcpp::wrap(corDist_x(x1, x2, y1, y2));
    return rcpp_result_gen;
END_RCPP
}
// corDists_x
NumericVector corDists_x(RawMatrix x, IntegerVector inx1, IntegerVector inx2);
RcppExport SEXP _iqtcat_corDists_x(SEXP xSEXP, SEXP inx1SEXP, SEXP inx2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type inx1(inx1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type inx2(inx2SEXP);
    rcpp_result_gen = Rcpp::wrap(corDists_x(x, inx1, inx2));
    return rcpp_result_gen;
END_RCPP
}
// corPreIdenticals_x
List corPreIdenticals_x(RawMatrix x, IntegerVector inx1, IntegerVector inx2, const int step);
RcppExport SEXP _iqtcat_corPreIdenticals_x(SEXP xSEXP, SEXP inx1SEXP, SEXP inx2SEXP, SEXP stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type inx1(inx1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type inx2(inx2SEXP);
    Rcpp::traits::input_parameter< const int >::type step(stepSEXP);
    rcpp_result_gen = Rcpp::wrap(corPreIdenticals_x(x, inx1, inx2, step));
    return rcpp_result_gen;
END_RCPP
}
// corIdenticals_x
List corIdenticals_x(RawMatrix x, IntegerVector inx1, IntegerVector inx2, IntegerVector clustIdx);
RcppExport SEXP _iqtcat_corIdenticals_x(SEXP xSEXP, SEXP inx1SEXP, SEXP inx2SEXP, SEXP clustIdxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type inx1(inx1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type inx2(inx2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type clustIdx(clustIdxSEXP);
    rcpp_result_gen = Rcpp::wrap(corIdenticals_x(x, inx1, inx2, clustIdx));
    return rcpp_result_gen;
END_RCPP
}
// joinCorIdenticals_x
List joinCorIdenticals_x(int n, List preclust, List ClustMedo);
RcppExport SEXP _iqtcat_joinCorIdenticals_x(SEXP nSEXP, SEXP preclustSEXP, SEXP ClustMedoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< List >::type preclust(preclustSEXP);
    Rcpp::traits::input_parameter< List >::type ClustMedo(ClustMedoSEXP);
    rcpp_result_gen = Rcpp::wrap(joinCorIdenticals_x(n, preclust, ClustMedo));
    return rcpp_result_gen;
END_RCPP
}
// corClarans_x
List corClarans_x(RawMatrix x, IntegerVector inx1, IntegerVector inx2, const int k, const int maxNeigbours);
RcppExport SEXP _iqtcat_corClarans_x(SEXP xSEXP, SEXP inx1SEXP, SEXP inx2SEXP, SEXP kSEXP, SEXP maxNeigboursSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type inx1(inx1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type inx2(inx2SEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const int >::type maxNeigbours(maxNeigboursSEXP);
    rcpp_result_gen = Rcpp::wrap(corClarans_x(x, inx1, inx2, k, maxNeigbours));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_iqtcat_isInteraction", (DL_FUNC) &_iqtcat_isInteraction, 2},
    {"_iqtcat_interactionIndices", (DL_FUNC) &_iqtcat_interactionIndices, 4},
    {"_iqtcat_testIndices", (DL_FUNC) &_iqtcat_testIndices, 6},
    {"_iqtcat_cor_x", (DL_FUNC) &_iqtcat_cor_x, 4},
    {"_iqtcat_corDist_x", (DL_FUNC) &_iqtcat_corDist_x, 4},
    {"_iqtcat_corDists_x", (DL_FUNC) &_iqtcat_corDists_x, 3},
    {"_iqtcat_corPreIdenticals_x", (DL_FUNC) &_iqtcat_corPreIdenticals_x, 4},
    {"_iqtcat_corIdenticals_x", (DL_FUNC) &_iqtcat_corIdenticals_x, 4},
    {"_iqtcat_joinCorIdenticals_x", (DL_FUNC) &_iqtcat_joinCorIdenticals_x, 3},
    {"_iqtcat_corClarans_x", (DL_FUNC) &_iqtcat_corClarans_x, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_iqtcat(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
