# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

isInteraction <- function(x1, x2) {
    .Call('_iqtcat_isInteraction', PACKAGE = 'iqtcat', x1, x2)
}

interactionIndices <- function(x, chr, pos, minDist) {
    .Call('_iqtcat_interactionIndices', PACKAGE = 'iqtcat', x, chr, pos, minDist)
}

testIndices <- function(x, inx1, inx2, chr, pos, minDist) {
    .Call('_iqtcat_testIndices', PACKAGE = 'iqtcat', x, inx1, inx2, chr, pos, minDist)
}

cor_x <- function(x1, x2, y1, y2) {
    .Call('_iqtcat_cor_x', PACKAGE = 'iqtcat', x1, x2, y1, y2)
}

corDist_x <- function(x1, x2, y1, y2) {
    .Call('_iqtcat_corDist_x', PACKAGE = 'iqtcat', x1, x2, y1, y2)
}

corDists_x <- function(x, inx1, inx2) {
    .Call('_iqtcat_corDists_x', PACKAGE = 'iqtcat', x, inx1, inx2)
}

corPreIdenticals_x <- function(x, inx1, inx2, step) {
    .Call('_iqtcat_corPreIdenticals_x', PACKAGE = 'iqtcat', x, inx1, inx2, step)
}

corIdenticals_x <- function(x, inx1, inx2, clustIdx) {
    .Call('_iqtcat_corIdenticals_x', PACKAGE = 'iqtcat', x, inx1, inx2, clustIdx)
}

joinCorIdenticals_x <- function(n, preclust, ClustMedo) {
    .Call('_iqtcat_joinCorIdenticals_x', PACKAGE = 'iqtcat', n, preclust, ClustMedo)
}

corClarans_x <- function(x, inx1, inx2, k, maxNeigbours) {
    .Call('_iqtcat_corClarans_x', PACKAGE = 'iqtcat', x, inx1, inx2, k, maxNeigbours)
}

